#高可用3个节点，正确。
#应用名称及验证账号
spring: 
  application: 
    name: eureka
    
  security: 
    user: 
      name: root
      password: root

logging:
  level:
    root: info
    
---
spring:
  profiles: 7901
server: 
  port: 7901
eureka:
  instance:
    hostname: localhost  
  client:
    #设置服务注册中心的URL
    service-url:                      
      defaultZone: http://root:root@localhost:7902/eureka/,http://root:root@localhost:7903/eureka/
---    
spring:
  profiles: 7902
server: 
  port: 7902
eureka:
  instance:
    hostname: localhost  
  client:
       #设置服务注册中心的URL
    service-url:                      
      defaultZone: http://root:root@localhost:7903/eureka/,http://root:root@localhost:7901/eureka/
---    
spring:
  profiles: 7903
server: 
  port: 7903
eureka:
  instance:
    hostname: localhost
  client:
       #设置服务注册中心的URL
    service-url:                      
      defaultZone: http://root:root@localhost:7901/eureka/,http://root:root@localhost:7902/eureka/
