#单点注册中心

#服务端口
server:
  port: 8084

#应用名称及验证账号
spring:
  application:
    name: api-listen-order
  #是否向server注册服务，默认true
  cloud:
    service-registry:
      auto-registration:
        enabled: true

#注册中心
eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    #设置服务注册中心的URL
    service-url:
      defaultZone: http://root:root@localhost:7901/eureka/,http://root:root@localhost:7902/eureka/,http://root:root@localhost:7903/eureka/
  instance:
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    lease-renewal-interval-in-seconds: 1
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 1
    hostname: localhost
    #true表示，将自己的ip注册到Eureka Server上，不配置或false表示将所在操作系统hostname注册到eureka server上。
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server:port}
    metadata-map:
      user.name: root
      user.password: root
      yueyi: 2019
      a: b

#Admin监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS